services:
  mysql-sync:
    build: .
    container_name: mysql-sync
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8520}:8520"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
    networks:
      - default
      - shared

networks:
  shared:
    external: true
